<?php 

/**
* English translations used in Shift controller
*/

$lang['shortcode'] = "en";

// HEADER
$lang['add'] = "Add shift";
$lang['report'] = "View report";
$lang['pdf'] = "Printable report";
$lang['profile'] = "Edit user profile";
$lang['sign_out'] = "Sign out";

$lang['ph_date'] = "Date";
$lang['ph_month'] = "Month";
$lang['ph_start'] = "Start";
$lang['ph_end'] = "End";
$lang['ph_bonus'] = "Bonus";
$lang['ph_note'] = "Note";

$lang['btn_add'] = "Save";
$lang['btn_show'] = "Show";

$lang['title_add'] = "Add new shift";
$lang['title_report'] = "Shift report";
$lang['title_report_period'] = "Select report period";

// SHIFT LISTING
$lang['day'] = "Day";
$lang['night'] = "Night";
$lang['sunday'] = "Sunday";
$lang['sunday_night'] = "Sunday night";
$lang['holiday'] = "Holiday";
$lang['holiday_night'] = "Holiday night";
$lang['bonus'] = "Bonus";
$lang['date'] = "Date";
$lang['time'] = "Time";
$lang['total'] = "Total";

$lang['lbl_details'] = "Details";
$lang['lbl_total'] = "Total";
$lang['lbl_time'] = "Time";
$lang['lbl_note'] = "Note";

$lang['dlg_btn_close'] = "Close";
$lang['dlg_btn_save'] = "Save";
$lang['dlg_btn_delete'] = "Delete";
$lang['dlg_edit_title'] = "Edit shift";
$lang['dlg_delete_title'] = "Delete shift";
$lang['dlg_delete_msg'] = "Delete shift on ";

$lang['generated_by'] = "Report is generated by ";
