<?php 

/**
* English translations used in Shift controller
*/

$lang['shortcode'] = "en";

// HEADER
$lang['add'] = "Add shift";
$lang['report'] = "View report";
$lang['pdf'] = "Printable report";
$lang['stats'] = "Statistics";
$lang['profile'] = "Edit user profile";
$lang['sign_out'] = "Sign out";
$lang['feedback'] = "Feedback";

$lang['stats_totals_t'] = "Salary";
$lang['stats_totals_series'] = "Salary";
$lang['stats_hours_t'] = "Hour distribution";
$lang['stats_avg_t'] = "Average hourly earning";
$lang['stats_avg_series'] = "Average hourly earning";

$lang['month_01'] = "Jan";
$lang['month_02'] = "Feb";
$lang['month_03'] = "Mar";
$lang['month_04'] = "Apr";
$lang['month_05'] = "May";
$lang['month_06'] = "Jun";
$lang['month_07'] = "Jul";
$lang['month_08'] = "Aug";
$lang['month_09'] = "Sep";
$lang['month_10'] = "Oct";
$lang['month_11'] = "Nov";
$lang['month_12'] = "Dec";

$lang['ph_date'] = "Date";
$lang['ph_month'] = "Month";
$lang['ph_start'] = "Start";
$lang['ph_end'] = "End";
$lang['ph_bonus'] = "Bonus";
$lang['ph_note'] = "Note";

$lang['btn_add'] = "Save";
$lang['btn_show'] = "Show";

$lang['title_add'] = "Add new shift";
$lang['title_report'] = "Shift report";
$lang['title_report_period'] = "Select report period";

// SHIFT LISTING
$lang['day'] = "Day";
$lang['night'] = "Night";
$lang['sunday'] = "Sunday";
$lang['sunday_night'] = "Sunday night";
$lang['holiday'] = "Holiday";
$lang['holiday_night'] = "Holiday night";
$lang['bonus'] = "Bonus";
$lang['date'] = "Date";
$lang['time'] = "Time";
$lang['total'] = "Total";

$lang['lbl_details'] = "Details";
$lang['lbl_total'] = "Total";
$lang['lbl_time'] = "Time";
$lang['lbl_note'] = "Note";

$lang['dlg_btn_close'] = "Close";
$lang['dlg_btn_save'] = "Save";
$lang['dlg_btn_delete'] = "Delete";
$lang['dlg_edit_title'] = "Edit shift";
$lang['dlg_delete_title'] = "Delete shift";
$lang['dlg_delete_msg'] = "Delete shift on ";

$lang['generated_by'] = "Report is generated by ";
